services:
  yapa-backend:
    container_name: yapa-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      DATABASE_URL: /var/lib/yapa/database.sqlite
      DOMAIN: localhost
      APPLE_CLIENT_ID: org.example
      APPLE_TEAM_ID: ABC123WXYZ
      APPLE_CLIENT_KEY_ID: ABC123WXYZ
      APPLE_CLIENT_KEY: |
        -----BEGIN PRIVATE KEY-----
        -----END PRIVATE KEY-----
      GOOGLE_CLIENT_ID: 123
      GOOGLE_CLIENT_SECRET:
    volumes:
      - ./data/backend:/var/lib/yapa
    expose:
      - 8080
  yapa-frontend:
    container_name: yapa-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    expose:
      - 3000
  yapa-server:
    container_name: yapa-server
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    volumes:
      - ./data/server:/data
      - caddy_config:/config
    ports:
      - 8080:8080

volumes:
  caddy_config: