// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type AuthMethod struct {
	ID         int64
	Userid     []byte
	Created    int64
	Provider   string
	Identifier string
	Secret     string
}

type Permission struct {
	ID   int64
	Name string
}

type Provider struct {
	ID   int64
	Type string
}

type Session struct {
	ID      []byte
	Created int64
	Updated int64
	Expires int64
	Data    []byte
}

type User struct {
	ID      []byte
	Created int64
	Email   string
	Name    string
}

type UserPermission struct {
	ID         int64
	Userid     []byte
	Created    int64
	Permission string
}
